# Generated by Django 2.0.4 on 2018-06-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsection',
            name='picture_link',
            field=models.CharField(default='/forum/images/default_section.png', max_length=250),
        ),
    ]
