# Generated by Django 2.0.4 on 2018-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180618_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsection',
            name='section_link',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
