# Generated by Django 2.0.4 on 2018-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180620_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsection',
            name='picture_link',
            field=models.CharField(default='default_section.png', max_length=250),
        ),
    ]
