# Generated by Django 2.0.4 on 2018-06-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_auto_20180627_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsection',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ForumSection_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumsection',
            name='subscribers',
            field=models.ManyToManyField(related_name='ForumSection_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
