# Generated by Django 2.0.4 on 2018-07-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20180702_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_time', '-created_time']},
        ),
    ]
