# Generated by Django 2.0.4 on 2018-07-10 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_auto_20180710_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
